[package]
name = "solana-hello-world"
version = "0.0.1"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "1.14.5"

[lib]
name = "helloworld"
crate-type = ["cdylib", "lib"]